### ISSUE TITLE
Offline package usage breaks for production build - cannot find module @iconify/vue/dist/offline (vite + vue 3)

### ISSUE THREAD

**Issue by awacode21** [iconify/iconify#115]
As there is the already mentioned ([SSR issue](https://github.com/iconify/iconify/issues/114)) with the 'online' usage i tried to workaround it with the offline usage.
It works perfectly fine for dev server in localhost. But when building or generating the app for production, it says it is not able to find the offline module of iconify. But when i check the node_modules folder it is there.

Usage:
```
import { Icon } from '@iconify/vue/dist/offline';
import EmailIcon from '@iconify-icons/mdi/email';
import PhoneIcon from '@iconify-icons/mdi/phone';
import CellphoneIcon from '@iconify-icons/mdi/cellphone';
```

Error message:
```
awacode@awacode-MBP13 bivignano % npm run generate

> bivignano@0.0.0 generate
> vite build --ssrManifest --outDir dist && npm run build:server && node prerender

vite v2.8.4 building for production...
✓ 108 modules transformed.
dist/assets/OptimusPrinceps.fc66926b.woff   24.65 KiB
dist/assets/OptimusPrinceps.9b8022e9.eot    40.64 KiB
dist/assets/OptimusPrinceps.06728ee9.ttf    40.45 KiB
dist/index.html                             0.99 KiB
dist/ssr-manifest.json                      13.31 KiB
dist/assets/index.79b58e15.js               10.65 KiB / gzip: 4.41 KiB
dist/assets/headline.3936d964.js            0.25 KiB / gzip: 0.20 KiB
dist/assets/index.07a5fe3d.css              2.46 KiB / gzip: 0.96 KiB
dist/assets/vendor.ab91a02e.js              113.06 KiB / gzip: 44.30 KiB

> bivignano@0.0.0 build:server
> vite build --ssr src/entry-server.js --outDir dist/server

vite v2.8.4 building SSR bundle for production...
✓ 21 modules transformed.
dist/server/entry-server.js   29.84 KiB
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error: Cannot find module '/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/@iconify/vue/dist/offline'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Module.<anonymous> (/Users/awacode/code/customers/bivignano/vue3/bivignano/dist/server/entry-server.js:28:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/@iconify/vue/package.json'
}
```

**Comment by cyberalien** [comment]
Try importing from '@iconify/vue/offline'. If build script supports exports field in package.json, it should work.

**Comment by awacode21** [comment]
When i try with that path:

```
import { Icon } from '@iconify/vue/offline';
import EmailIcon from '@iconify-icons/mdi/email';
import PhoneIcon from '@iconify-icons/mdi/phone';
import CellphoneIcon from '@iconify-icons/mdi/cellphone';
```

it is giving me the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/@iconify-icons/mdi/email.js from /Users/awacode/code/customers/bivignano/vue3/bivignano/dist/server/entry-server.js not supported.
Instead change the require of email.js in /Users/awacode/code/customers/bivignano/vue3/bivignano/dist/server/entry-server.js to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/Users/awacode/code/customers/bivignano/vue3/bivignano/dist/server/entry-server.js:29:17)
    at /Users/awacode/code/customers/bivignano/vue3/bivignano/server.js:64:18
    at Layer.handle [as handle_request] (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:323:13)
    at /Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:284:7
    at param (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:360:14)
    at param (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:416:3)
    at next (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:390:28)
    at SendStream.error (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/send/index.js:270:17)
    at SendStream.redirect (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/serve-static/index.js:185:12)
    at SendStream.emit (node:events:390:28)
    at SendStream.redirect (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/send/index.js:479:10)
    at onstat (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/send/index.js:727:41)
    at FSReqCallback.oncomplete (node:fs:199:5)
```

**Comment by cyberalien** [comment]
What version of Node are you using?

**Comment by awacode21** [comment]
```
awacode@awacode-MBP13 bivignano % node --version
v16.13.1
awacode@awacode-MBP13 bivignano % npm --version
8.1.2
awacode@awacode-MBP13 bivignano %
```

**Comment by cyberalien** [comment]
Even though your code uses imports, looks like they are compiled to CommonJS, in which case it cannot use ES modules.

There are several solutions:
1. Switch to ES. It could be a big task, but more and more libraries are moving to ES, so eventually this will have to be done anyway. 
2. Use CommonJS version of icons. Instead of `@iconify-icons/mdi` use `@iconify/icons-mdi` package. It is identical, but for CommonJS.

**Comment by awacode21** [comment]
hm, i have a completely new setup with vite and vue3 using ES. That is really weired.

**Comment by cyberalien** [comment]
Try adding `"type": "module",` to package.json

**Comment by awacode21** [comment]
```
awacode@awacode-MBP13 bivignano % npm run build

> bivignano@0.0.0 build
> vue-tsc --noEmit && npm run build:client && npm run build:server


> bivignano@0.0.0 build:client
> vite build --ssrManifest --outDir dist/client

failed to load config from /Users/awacode/code/customers/bivignano/vue3/bivignano/vite.config.ts
error during build:
TypeError: eslintPlugin is not a function
    at file:///Users/awacode/code/customers/bivignano/vue3/bivignano/vite.config.ts.js?t=1645980949604:10:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/vite/dist/node/chunks/dep-971d9e33.js:71303:31)
    at async resolveConfig (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/vite/dist/node/chunks/dep-971d9e33.js:70850:28)
    at async doBuild (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38955:20)
    at async build (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38943:16)
    at async CAC.<anonymous> (/Users/awacode/code/customers/bivignano/vue3/bivignano/node_modules/vite/dist/node/cli.js:738:9)
```

**Comment by cyberalien** [comment]
Published update for Vue component, it should fix import from `dist/offline`, pointing to .mjs file for ES import, to .js when used with require().

As for last error, it is in our build process and I can't help with that.

**Comment by cyberalien** [comment]
If you want to use offline component, there is an alternative: https://github.com/antfu/unplugin-icons 

It is built by one of Vue core developers, uses Iconify for icon data.

My component is more oriented towards downloading icon data on demand, offline version was an attempt to make component without API, but `unplugin-icons` is much better for it.

**Comment by awacode21** [comment]
thank you so much for this really helpful tip with unplugin-icons. it's working perfectly fine for me :-)

**Comment by userquin** [comment]
@awacode21 since you are using vite you can also check preset icons on unocss, your icons will go to your css, no more sfc for icons.

Preset icons is also using iconify for icon data, and with an extra depedency, preset uno, you will also have tailwind styles, just check the repo.
