### ISSUE TITLE
use with unplugin-icon and vue3 and vite, but throw iconify.mjs not found.

### ISSUE THREAD

**Issue by radiorz** [iconify/iconify#145]
```
[vite] error while updating dependencies:
Error: ENOENT: no such file or directory, open 'D:/code/frontend-demo/node_modules/@iconify/vue/dist/iconify.mjs'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at runOptimizeDeps (D:\code\frontend-demo\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:39538:46)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9)
    at async runOptimizer (D:\code\frontend-demo\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:59545:38)
Vite Error, /node_modules/.vite/deps/theme-change.js?v=1febecd5 optimized info should be defined

```

**Comment by cyberalien** [comment]
`unplugin-icon` and `@iconify/vue` are two completely different packages.

**Comment by radiorz** [comment]
thanks。 In my project i install @iconify/vue before and maybe i dont remove it totally. I clean the node_modules and reinstall the project works good.
