### ISSUE TITLE
@iconify-icon/solid:  Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by sysmat** [iconify/iconify#209]
- deps

```json
"devDependencies": {
    "@iconify-icon/solid": "^1.0.7",
    "@iconify/json": "^2.2.42",
    "@solidjs/testing-library": "^0.7.0",
    "@testing-library/user-event": "^14.4.3",
    "@vitest/coverage-c8": "^0.29.8",
    "autoprefixer": "^10.4.14",
    "jsdom": "^21.1.1",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.0",
    "turbo": "^1.8.8",
    "typescript": "^5.0.2",
    "vite": "^4.2.1",
    "vite-plugin-solid": "2.6.1",
    "vitest": "^0.29.8"
  },
  "dependencies": {
    "@felte/solid": "^1.2.7",
    "@solid-primitives/clipboard": "^1.5.3",
    "@solid-primitives/connectivity": "^0.3.11",
    "@solid-primitives/geolocation": "^1.4.7",
    "@solid-primitives/keyboard": "^1.0.11",
    "@solidjs/router": "^0.8.2",
    "daisyui": "^2.51.5",
    "hotkeys-js": "^3.10.1",
    "ky": "^0.33.3",
    "radash": "^10.8.1",
    "solid-js": "^1.7.0",
    "zod": "^3.21.4"
  }
```
- when upgrading error happened

```
@iconify/json  ^2.2.41  →  ^2.2.42
 solid-js       ^1.6.16  →   ^1.7.0

```
- error stack browser console

```
Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.
    at iconify.jsx:15:5
    at untrack (dev.js:430:33)
    at iconify.jsx:15:5
    at Icon (iconify.jsx:16:208)
    at dev.js:548:12
    at untrack (dev.js:434:12)
    at Object.fn (dev.js:544:37)
    at runComputation (dev.js:695:22)
    at updateComputation (dev.js:678:3)
    at devComponent (dev.js:555:3)
```

**Comment by sysmat** [comment]
- hm, maybe is problem my `tsconfig.json`

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": ["vite/client"],
    "noEmit": true,
    "isolatedModules": true
  }
}

```

**Comment by cyberalien** [comment]
That's almost identical to mine, except for `strict` option, but after adding it I still don't see any issues.

Try replacing `iconify.tsx` with this, please tell me if it helps:

```tsx
import type { JSX } from 'solid-js';

import type {
	IconifyIcon,
	IconifyIconProperties,
	IconifyIconAttributes,
	IconifyIconHTMLElement,
} from 'iconify-icon';

/**
 * Export types
 */
export type {
	IconifyStorageFunctions,
	IconifyBuilderFunctions,
	IconifyBrowserCacheFunctions,
	IconifyAPIFunctions,
	IconifyAPIInternalFunctions,
} from 'iconify-icon';

// JSON stuff
export type { IconifyIcon, IconifyJSON, IconifyIconName } from 'iconify-icon';

// Customisations
export type { IconifyIconCustomisations, IconifyIconSize } from 'iconify-icon';

// API
export type {
	IconifyAPIConfig,
	IconifyIconLoaderCallback,
	IconifyIconLoaderAbort,
	IconifyAPIModule,
	GetAPIConfig,
	IconifyAPIPrepareIconsQuery,
	IconifyAPISendQuery,
	PartialIconifyAPIConfig,
	IconifyAPIQueryParams,
	IconifyAPICustomQueryParams,
} from 'iconify-icon';

// Builder functions
export type { IconifyIconBuildResult } from 'iconify-icon';

// Browser cache
export type { IconifyBrowserCacheType } from 'iconify-icon';

// Component types
export type {
	IconifyIconAttributes,
	IconifyIconProperties,
	IconifyRenderMode,
	IconifyIconHTMLElement,
} from 'iconify-icon';

/**
 * Export functions
 */
export {
	enableCache,
	disableCache,
	iconExists,
	getIcon,
	listIcons,
	addIcon,
	addCollection,
	calculateSize,
	buildIcon,
	loadIcons,
	loadIcon,
	addAPIProvider,
	appendCustomStyle,
	_api,
} from 'iconify-icon';

/**
 * Properties for Solid component
 */
type BaseElementProps = JSX.IntrinsicElements['span'];
export interface IconifyIconProps
	extends BaseElementProps,
		IconifyIconProperties {
	// Rotation can be string or number
	rotate?: string | number;
}

interface SolidJSIconifyIconProps extends IconifyIconProps {
	// Copy all props with 'attr:' prefix for Solid
	'attr:icon': IconifyIconProps['icon'];
	'attr:mode': IconifyIconProps['mode'];
	'attr:inline': IconifyIconProps['inline'];
	'attr:rotate': IconifyIconProps['rotate'];
	'attr:flip': IconifyIconProps['flip'];
	'attr:width': IconifyIconProps['width'];
	'attr:height': IconifyIconProps['height'];
	'attr:preserveAspectRatio': IconifyIconProps['preserveAspectRatio'];
}

declare global {
	namespace JSX {
		interface IntrinsicElements {
			'iconify-icon': SolidJSIconifyIconProps;
		}
	}
}

/**
 * Solid component
 */
export function Icon(props: IconifyIconProps): JSX.Element {
	let {
		icon,
		mode,
		inline,
		rotate,
		flip,
		width,
		height,
		preserveAspectRatio,
	} = props;

	// Convert icon to string
	if (typeof icon === 'object') {
		icon = JSON.stringify(icon);
	}

	return (
		<iconify-icon
			attr:icon={icon}
			attr:mode={mode}
			attr:inline={inline}
			attr:rotate={rotate}
			attr:flip={flip}
			attr:width={width}
			attr:height={height}
			attr:preserveAspectRatio={preserveAspectRatio}
			{...props}
		/>
	);
}
```

**Comment by cyberalien** [comment]
oops.. sorry, that's source file. Replace `iconify.d.ts` with this:
```ts
import type { JSX } from 'solid-js';
import type { IconifyIconProperties } from 'iconify-icon';
/**
 * Export types
 */
export type { IconifyStorageFunctions, IconifyBuilderFunctions, IconifyBrowserCacheFunctions, IconifyAPIFunctions, IconifyAPIInternalFunctions, } from 'iconify-icon';
export type { IconifyIcon, IconifyJSON, IconifyIconName } from 'iconify-icon';
export type { IconifyIconCustomisations, IconifyIconSize } from 'iconify-icon';
export type { IconifyAPIConfig, IconifyIconLoaderCallback, IconifyIconLoaderAbort, IconifyAPIModule, GetAPIConfig, IconifyAPIPrepareIconsQuery, IconifyAPISendQuery, PartialIconifyAPIConfig, IconifyAPIQueryParams, IconifyAPICustomQueryParams, } from 'iconify-icon';
export type { IconifyIconBuildResult } from 'iconify-icon';
export type { IconifyBrowserCacheType } from 'iconify-icon';
export type { IconifyIconAttributes, IconifyIconProperties, IconifyRenderMode, IconifyIconHTMLElement, } from 'iconify-icon';
/**
 * Export functions
 */
export { enableCache, disableCache, iconExists, getIcon, listIcons, addIcon, addCollection, calculateSize, buildIcon, loadIcons, loadIcon, addAPIProvider, appendCustomStyle, _api, } from 'iconify-icon';
/**
 * Properties for Solid component
 */
type BaseElementProps = JSX.IntrinsicElements['span'];
export interface IconifyIconProps extends BaseElementProps, IconifyIconProperties {
    rotate?: string | number;
}
interface SolidJSIconifyIconProps extends IconifyIconProps {
    'attr:icon': IconifyIconProps['icon'];
    'attr:mode': IconifyIconProps['mode'];
    'attr:inline': IconifyIconProps['inline'];
    'attr:rotate': IconifyIconProps['rotate'];
    'attr:flip': IconifyIconProps['flip'];
    'attr:width': IconifyIconProps['width'];
    'attr:height': IconifyIconProps['height'];
    'attr:preserveAspectRatio': IconifyIconProps['preserveAspectRatio'];
}
declare global {
    namespace JSX {
        interface IntrinsicElements {
            'iconify-icon': SolidJSIconifyIconProps;
        }
    }
}
/**
 * Solid component
 */
export declare function Icon(props: IconifyIconProps): JSX.Element;
```

**Comment by sysmat** [comment]
@cyberalien even when replace error still persist

```
TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.
    at iconify.jsx:15:5
```

**Comment by cyberalien** [comment]
Can you make a test repo with bug?

**Comment by sysmat** [comment]
https://stackblitz.com/edit/solidjs-templates-uv8qzv?file=package.json

**Comment by cyberalien** [comment]
Thanks! I can see error

**Comment by cyberalien** [comment]
Test case to show actual bug:

```tsx
import { Component, createSignal } from "solid-js";
import "iconify-icon";

const Count: Component = () => {
  const [count, setCount] = createSignal(0);
  const icon = '<iconify-icon icon="ic:baseline-minus"></iconify-icon>';
  return (
    <div>
      <span innerHTML={icon}></span>
      <output>Count: {count}</output>
      <iconify-icon icon="ic:baseline-plus"></iconify-icon>
    </div>
  );
};

export default Count;
```
That code bugs out with same error. It doesn't use web component wrapper, instead, it uses actual web component.

It has 2 icons:
- One as `innerHTML` of span element.
- One as is.

If second icon is commented out, error disappears and first icon is rendered correctly. So web component does work, Solid just bugs out when working with web components.

I suggest reporting bug to Solid, using test code I've posted above.

Temporary workaround until Solid bug is fixed, is to use `span` element with icon as `innerHTML` property. You can assign event listeners to `span`, all other attributes can be used in web component string. Use `iconify-icon` package instead of `@iconify-icon/solid`, import whole package.

**Comment by sysmat** [comment]
@cyberalien maybe is better that you report bug to Solid you have more knowledge about iconify-icon

**Comment by cyberalien** [comment]
Sure

**Comment by cyberalien** [comment]
Though I'm still very confused why I'm not seeing same error in `iconify-icon-demo/solid-demo` in this repository. So something is different about setup of your package, but I'm not sure what.

**Comment by cyberalien** [comment]
Same failing test without Iconify web component, using very basic web component:

```tsx
import { Component, createSignal } from "solid-js";

class TestComponent extends HTMLElement {
  constructor() {
    super();
    const root = this.attachShadow({
      mode: "open",
    });
    root.innerHTML = " test ";
  }
}
customElements.define("test-component", TestComponent);

const Count: Component = () => {
  const [count, setCount] = createSignal(0);
  const innerHTML = "<test-component></test-component>";
  return (
    <div>
      <span innerHTML={innerHTML}></span>
      <output>Count: {count}</output>
      <test-component></test-component>
    </div>
  );
};

export default Count;
```

**Comment by sysmat** [comment]
i started as stackblitz solid template

**Comment by cyberalien** [comment]
> i started as stackblitz solid template

Thanks. I'll make a test case from that!

**Comment by cyberalien** [comment]
I think it's something else.

Forked StackBlitz template, added same code, it works fine: https://stackblitz.com/edit/solid-template-rjjtvy?file=src/index.jsx

**Comment by sysmat** [comment]
aha, but this is not using typescript

**Comment by cyberalien** [comment]
Works fine with ts and latest dependencies too: https://stackblitz.com/edit/vitejs-vite-ycjv2o?file=src/App.tsx

**Comment by cyberalien** [comment]
Closing this. Can't reproduce.

**Comment by tutods** [comment]
Anyone already face this error on Solid Start:
```
TypeError: e is not a function
    at Hs (iconify-8xfz3JeK.js:1:21467)
    at Object.fn (iconify-8xfz3JeK.js:1:26792)
    at _o (iconify-8xfz3JeK.js:1:5965)
    at bt (iconify-8xfz3JeK.js:1:5738)
    at Object.Ls (iconify-8xfz3JeK.js:1:4774)
    at Object.fn (iconify-8xfz3JeK.js:1:20868)
    at _o (iconify-8xfz3JeK.js:1:5965)
    at bt (iconify-8xfz3JeK.js:1:5738)
    at qe (iconify-8xfz3JeK.js:1:1114)
    at xn (iconify-8xfz3JeK.js:1:20857)
```

I'm trying to deploy my website, but I'm always getting `Error | Uncaught Client Exception`
