### ISSUE TITLE
error importing icon

### ISSUE THREAD

**Issue by tasiotas** [iconify/iconify#238]
I have one icon with problematic syntax that cleanupCVG is having trouble.

I believe this is the line that is causing error:
`  <text x="465.1" y="269.5" fill="#bd0728" stroke="#fff" stroke-width="1.6" font-family="helvetica" font-size="25.6" transform="matrix(1.33 0 0 1.33 -363 -108)"><tspan>G</tspan></text>`

I am importing it via directory import described here. I'm wondering why try/catch isn't catching it properly.
https://iconify.design/docs/libraries/tools/import/directory.html#examples

Thank you

```
nuxt  |  ERROR  [unhandledRejection] Unexpected element: <text>
nuxt  | 
nuxt  |   at node_modules/@iconify/tools/lib/svg/cleanup/bad-tags.cjs:53:13
nuxt  |   at isSync (node_modules/@iconify/tools/lib/svg/parse.cjs:65:7)
nuxt  |   at checkNode (node_modules/@iconify/tools/lib/svg/parse.cjs:19:5)
nuxt  |   at next (node_modules/@iconify/tools/lib/svg/parse.cjs:35:9)
nuxt  |   at next (node_modules/@iconify/tools/lib/svg/parse.cjs:33:18)
nuxt  |   at node_modules/@iconify/tools/lib/svg/parse.cjs:37:7
nuxt  |   at isSync (node_modules/@iconify/tools/lib/svg/parse.cjs:66:7)
nuxt  |   at checkNode (node_modules/@iconify/tools/lib/svg/parse.cjs:19:5)
nuxt  |   at next (node_modules/@iconify/tools/lib/svg/parse.cjs:35:9)
nuxt  |   at next (node_modules/@iconify/tools/lib/svg/parse.cjs:33:18)
```
![gu](https://github.com/iconify/iconify/assets/9046931/d8c75d2e-3b72-4747-8d51-8e1d8a82f624)

**Comment by cyberalien** [comment]
That's correct behaviour. 

Tools are slightly opinionated, designed to generate public icon sets that are used by many users. Text is not allowed because it renders differently for different users.

If you don't want it to throw errors, set `ignoreImportErrors: true` in options:
```js
importDirectory(dir, { ignoreImportErrors: true })
```

**Comment by tasiotas** [comment]
Thank you.

I did see this option in docs, its true on default.
I tried setting it explicitly, I still get the same error.

**Comment by cyberalien** [comment]
If option doesn't work, that's a bug. I'll test it.

Moving this issue to correct repository.
