### ISSUE TITLE
Prettier formatting error when using `@iconify/tailwind` and `@iconify/tools`

### ISSUE THREAD

**Issue by sadeghbarati** [iconify/iconify#242]
Prettier 2, 3 error

```
["ERROR" - 1:59:07 PM] Error formatting document.
["ERROR" - 1:59:07 PM] ENOENT: no such file or directory, scandir 'icons/' <------
Error: ENOENT: no such file or directory, scandir 'icons/'
    at Object.readdirSync (node:fs:1454:3)
    at t.readdirSync (node:electron/js2c/asar_bundle:2:10837)
    at scan (d:\Sadegh\Temps\project\node_modules\@iconify\tools\lib\misc\scan.cjs:68:22)
    at Object.scanDirectorySync (d:\Sadegh\Temps\project\node_modules\@iconify\tools\lib\misc\scan.cjs:99:3)
    at importDirectorySync (d:\Sadegh\Temps\project\node_modules\@iconify\tools\lib\import\directory.cjs:118:27)
    at jiti (d:\Sadegh\Temps\project\node_modules\jiti\dist\jiti.js:1:245784)
    at d:\Sadegh\Temps\project\tailwind.config.js:2:20
    at jiti (d:\Sadegh\Temps\project\node_modules\jiti\dist\jiti.js:1:245784)
    at d:\Sadegh\Temps\project\node_modules\tailwindcss\lib\lib\load-config.js:37:30
```

---

I'm using latest `prettier` and [`prettier-plugin-tailwindcss`](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) 
and `@iconify/tools` to generate custom iconsets for `@iconify/tailwind`, also requiring `synchronous` functions

```ts
// tailwind.config.js
const {
  addDynamicIconSelectors,
} = require('@iconify/tailwind')
const {
  importDirectorySync,
  cleanupSVG,
  runSVGO,
} = require('@iconify/tools')

const customIconset = importDirectorySync('icons') // <------

customIconset.forEachSync((name, type) => {
  if (type !== 'icon') {
    return
  }
  const svg = customIconset.toSVG(name)
  if (!svg) {
    customIconset.remove(name)
    return
  }

  try {
    cleanupSVG(svg)
    runSVGO(svg)
  } catch (err) {
    console.error(`Error parsing ${name}:`, err)
    customIconset.remove(name)
    return
  }
  customIconset.fromSVG(name, svg)
})

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
      // ...
  },
  plugins: [
    addDynamicIconSelectors({
      iconSets: {
        customSets: customIconset.export(),
      },
    }),
  ],
}
```

**Comment by cyberalien** [comment]
Does directory `icons` exist?

**Comment by sadeghbarati** [comment]
Yes, I'll create repro

**Comment by sadeghbarati** [comment]
@cyberalien 

https://github.com/sadeghbarati/iconify-tool-prettier-error

**Comment by cyberalien** [comment]
Tested that repo, works fine. No errors at either build or dev.

Maybe you have wrong directory permissions?

**Comment by sadeghbarati** [comment]
Please install VSCode prettier extension then try "Format Document With... - Prettier"

**Comment by cyberalien** [comment]
Ignore that, should have checked prettier. It does throw error.

Solution:
```
const customIconset = importDirectorySync(__dirname + '/icons')
```

Looks like current directory is incorrect in prettier plugin.

**Comment by sadeghbarati** [comment]
It worked with your solution ❤️

**Comment by cyberalien** [comment]
Excellent.

Closing issue because it is an issue in Prettier plugin.
