### ISSUE TITLE
Problem with SvelteKit and iconify as dev-dependency

### ISSUE THREAD

**Issue by taffit** [iconify/iconify#78]
First of all: Thank you for this marvelous library!

The following problem is maybe not related to iconify, but as you already fixed the former issue in #67, it could be related to it. Unfortunately I have not enough experience to tell if it is related to this or not.

I try currently to migrate from Sapper to SvelteKit (I know, this is a moving target). I did install `@iconify/svelte@alpha' as suggested in the documentation and #67 . It works fine with the API or if I install iconify/an icons package to the prod-dependencies. However the combination of installing `@iconify/svelte@alpha` and an icon-package (`@iconify-icons/heroicons-outline` in my case) to the dev-dependencies and using the icon bundle produces the following error when running the `build` or `dev` target:

```
9:51:12 AM [vite] Error when evaluating SSR module /home/user/myproject/sveltekit/src/routes/index.svelte:
/home/user/myproject/sveltekit/node_modules/@iconify-icons/heroicons-outline/home.js:6
export default data;
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:102:7)
    at p._moduleCompile (/home/user/myproject/sveltekit/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/home/user/myproject/sveltekit/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at nodeRequire (/home/user/myproject/sveltekit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73479:17)
    at ssrImport (/home/user/myproject/sveltekit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73431:20)
Unexpected token 'export'
/home/user/myproject/sveltekit/node_modules/@iconify-icons/heroicons-outline/home.js:6
export default data;
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:102:7)
    at p._moduleCompile (/home/user/myproject/sveltekit/node_modules/jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/home/user/myproject/sveltekit/node_modules/jiti/dist/v8cache.js:2:2705)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at nodeRequire (/home/user/myproject/sveltekit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73479:17)
    at ssrImport (/home/user/myproject/sveltekit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73431:20)
```

`package.json`:
```json
{
  "name": "MyProject",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev --host --port 3001",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --check --plugin-search-dir=. . && eslint --ignore-path .gitignore .",
    "format": "prettier --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@iconify-icons/heroicons-outline": "^1.1.3",
    "@iconify/svelte": "^1.0.4",
    "@sveltejs/adapter-node": "^1.0.0-next.38",
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "svelte": "^3.34.0",
    "svelte-check": "^2.0.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0",
    "vite-plugin-windicss": "^1.2.7",
    "windicss": "^3.1.6"
  },
  "type": "module"
}
```

`svelte.config.js`:
```javascript
import preprocess from 'svelte-preprocess';
import node from '@sveltejs/adapter-node';
import WindiCSS from 'vite-plugin-windicss';

/** @type {import('@sveltejs/kit').Config} */
const config = {
        // Consult https://github.com/sveltejs/svelte-preprocess
        // for more information about preprocessors
        preprocess: preprocess(),

        kit: {
                // hydrate the <div id="svelte"> element in src/app.html
                target: '#svelte',
                adapter: node(),
                vite: {
      server: {
        host: "0.0.0.0",
        port: 3001
      },
      plugins: [
        WindiCSS.default(),
      ]
    }
        }
};

export default config;
```

`src/routes/index.svelte`:
```html
<script lang="ts">
  import Icon from "@iconify/svelte";
  import heroicons_outline_home from "@iconify-icons/heroicons-outline/home"
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
Just editing &hellip;...
<br/><br/>Just a test with a locally running instance &hellip;<br/>
<div class="text-blue-400">Tailwind CSS?</div>
<div class="red">WindiCSS!</div>
<div>Loving this <a href="https://iconify.design/">Iconify-library</a>! Brilliant!
<Icon
  class="h-6 w-6 text-indigo-400"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
  aria-hidden="true"
  inline={true}
  icon={heroicons_outline_home}
/>
<!--Icon
  class="h-6 w-6 text-indigo-400"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
  aria-hidden="true"
  inline={true}
  icon="heroicons-outline:home"
/-->
</div>

<style>
  .red { @apply text-red-400; }
</style>
```

`src/routes/__layout.svelte`:
```html
<script>
  import 'virtual:windi.css';
</script>

<slot></slot>
```

The rest is all default.    
As said, I'm not sure if iconify is the culprit or just my missing knowledge ;-). Maybe it can help.

Thank you once more for this great great library!

**Comment by cyberalien** [comment]
Yep, it is a nightmare to deal with. I've just rebuilt Iconify website using Svelte server side rendering: http://icon-sets.iconify.design/ and had to solve similar issue.

Issue is when using Svelte, it bundles everything nicely and prefers ES modules. When using server side rendering, it throws errors when using ES modules because Node.js still doesn't properly support ES modules.

Easiest solution is to switch to CommonJS module. Instead of `@iconify-icons/heroicons-outline` try `@iconify/icons-heroicons-outline`. Package is identical, but it uses CommonJS exports.

**Comment by taffit** [comment]
Thank you for your quick reply, @cyberalien. That works, indeed, so ticket can be closed.        

For noobs like me coming here, you have two alternatives:
- install everything in prod dependencies (`--save`/`-D` instead of `--save-dev`/`-s`) (not advised, if I understood correctly)
- or installing the CommonJS module as stated in [the documentation](https://docs.iconify.design/sources/npm/#packages) and @cyberalien's answer and importing it via `import homeIcon from '@iconify/icons-heroicons-outline/home.js';` (the tailing `.js` seems to be key here, I'm still learning).

Very confusing, this frontend development :-).

**Comment by cyberalien** [comment]
> Very confusing, this frontend development :-).

Actually, in your case it is both front end and server side. That's why it is confusing. 😄 When dealing with tools like SvelteKit, you need to think of how to make same code work in 2 environments.
